/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        /** Put Profile */
        put: operations["put_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/resume/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Resume */
        post: operations["extract_resume_api_profile_resume_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Create */
        post: operations["batch_create_api_jobs_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Job */
        post: operations["evaluate_job_api_jobs__job_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/reevaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reevaluate */
        post: operations["reevaluate_api_jobs_reevaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate Posting
         * @description Create (or find) a job and evaluate it — the paste flow and future browser-extension entry point.
         */
        post: operations["evaluate_posting_api_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluations */
        get: operations["list_evaluations_api_evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_api_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rebuild Request
         * @description Debug: rebuild the exact states and questions from stored inputs and current code (spec §6.7).
         */
        get: operations["rebuild_request_api_evaluations__evaluation_id__request_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/scoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scoring */
        get: operations["get_scoring_api_settings_scoring_get"];
        /** Put Scoring */
        put: operations["put_scoring_api_settings_scoring_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvoidedTechHeavy */
        AvoidedTechHeavy: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Points
             * @default 10
             */
            points: number;
            /**
             * Min Cross Platform Intensity
             * @default 2.5
             */
            min_cross_platform_intensity: number;
            /**
             * Cross Platform Families
             * @default [
             *       "flutter",
             *       "react_native"
             *     ]
             */
            cross_platform_families: string[];
            /**
             * Min Tech Centrality
             * @default 2
             */
            min_tech_centrality: number;
        };
        /** BatchIn */
        BatchIn: {
            /** Jobs */
            jobs: components["schemas"]["JobPostingIn"][];
            /**
             * Auto Evaluate
             * @default false
             */
            auto_evaluate: boolean;
        };
        /** BatchOut */
        BatchOut: {
            /** Created */
            created: number;
            /** Existing */
            existing: number;
            /** Evaluation Ids */
            evaluation_ids: string[];
        };
        /** BlockerFacts */
        BlockerFacts: {
            /** Needs Visa Sponsorship */
            needs_visa_sponsorship?: boolean | null;
            /** Can Meet Us Citizenship Requirement */
            can_meet_us_citizenship_requirement?: boolean | null;
            /** Can Meet Clearance Requirement */
            can_meet_clearance_requirement?: boolean | null;
        };
        /** Blockers */
        Blockers: {
            /**
             * Threshold
             * @default 0.8
             */
            threshold: number;
            /**
             * Possible Threshold
             * @default 0.5
             */
            possible_threshold: number;
            /**
             * @default {
             *       "enabled": true
             *     }
             */
            security_clearance: components["schemas"]["Toggle"];
            /**
             * @default {
             *       "enabled": true
             *     }
             */
            us_citizenship: components["schemas"]["Toggle"];
            /**
             * @default {
             *       "enabled": true
             *     }
             */
            no_sponsorship: components["schemas"]["Toggle"];
            /**
             * @default {
             *       "enabled": true
             *     }
             */
            relocation: components["schemas"]["Toggle"];
            /**
             * @default {
             *       "enabled": true
             *     }
             */
            onsite_location: components["schemas"]["Toggle"];
            /**
             * @default {
             *       "enabled": true,
             *       "avoid_core_probability": 0.8,
             *       "required_absent_probability": 0.9
             *     }
             */
            technology_mismatch: components["schemas"]["TechnologyMismatch"];
            /**
             * @default {
             *       "enabled": true,
             *       "min_steps_below": 2
             *     }
             */
            seniority_far_below: components["schemas"]["SeniorityFarBelow"];
        };
        /** Body_extract_resume_api_profile_resume_extract_post */
        Body_extract_resume_api_profile_resume_extract_post: {
            /** File */
            file: string;
        };
        /** CandidatePreferences */
        CandidatePreferences: {
            /**
             * Preferred Roles
             * @default []
             */
            preferred_roles: string[];
            /**
             * Preferred Locations
             * @default []
             */
            preferred_locations: string[];
            /**
             * Required Technologies
             * @default []
             */
            required_technologies: string[];
            /**
             * Preferred Technologies
             * @default []
             */
            preferred_technologies: string[];
            /**
             * Avoid Technologies
             * @default []
             */
            avoid_technologies: string[];
            /**
             * Preferred Levels
             * @default []
             */
            preferred_levels: ("junior" | "mid" | "senior" | "staff" | "principal" | "architect" | "manager" | "senior_manager" | "director_plus" | "unclear")[];
            /**
             * Preferred Role Families
             * @default []
             */
            preferred_role_families: ("android_native" | "mobile_general" | "ios" | "kotlin_multiplatform" | "flutter" | "react_native" | "backend" | "fullstack" | "engineering_management" | "other")[];
            /**
             * Avoided Role Families
             * @default []
             */
            avoided_role_families: ("android_native" | "mobile_general" | "ios" | "kotlin_multiplatform" | "flutter" | "react_native" | "backend" | "fullstack" | "engineering_management" | "other")[];
            /**
             * Preferred Domains
             * @default []
             */
            preferred_domains: ("fintech" | "healthcare" | "ecommerce" | "marketplace" | "social" | "media_streaming" | "automotive" | "ai_ml" | "enterprise" | "developer_tools" | "travel" | "delivery_logistics" | "gaming" | "government_defense" | "other")[];
            /**
             * Remote Preference
             * @default any
             * @enum {string}
             */
            remote_preference: "remote" | "hybrid" | "onsite" | "any";
            /**
             * Willing To Relocate
             * @default false
             */
            willing_to_relocate: boolean;
            /**
             * Management Preference
             * @default any
             * @enum {string}
             */
            management_preference: "ic" | "tech_lead" | "manager" | "any";
            /** Years Experience */
            years_experience?: number | null;
            /** Work Authorization Notes */
            work_authorization_notes?: string | null;
        };
        /** CandidateProfile */
        CandidateProfile: {
            /** Resume Text */
            resume_text: string;
            /**
             * @default {
             *       "preferred_roles": [],
             *       "preferred_locations": [],
             *       "required_technologies": [],
             *       "preferred_technologies": [],
             *       "avoid_technologies": [],
             *       "preferred_levels": [],
             *       "preferred_role_families": [],
             *       "avoided_role_families": [],
             *       "preferred_domains": [],
             *       "remote_preference": "any",
             *       "willing_to_relocate": false,
             *       "management_preference": "any"
             *     }
             */
            preferences: components["schemas"]["CandidatePreferences"];
            /** @default {} */
            blocker_facts: components["schemas"]["BlockerFacts"];
            /** Tracked Skills */
            tracked_skills: components["schemas"]["TrackedSkill"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Semantic Hash */
            semantic_hash: string;
        };
        /** CandidateProfileIn */
        CandidateProfileIn: {
            /** Resume Text */
            resume_text: string;
            /**
             * @default {
             *       "preferred_roles": [],
             *       "preferred_locations": [],
             *       "required_technologies": [],
             *       "preferred_technologies": [],
             *       "avoid_technologies": [],
             *       "preferred_levels": [],
             *       "preferred_role_families": [],
             *       "avoided_role_families": [],
             *       "preferred_domains": [],
             *       "remote_preference": "any",
             *       "willing_to_relocate": false,
             *       "management_preference": "any"
             *     }
             */
            preferences: components["schemas"]["CandidatePreferences"];
            /** @default {} */
            blocker_facts: components["schemas"]["BlockerFacts"];
            /** Tracked Skills */
            tracked_skills: components["schemas"]["TrackedSkill"][];
        };
        /** ChoiceSignal */
        ChoiceSignal: {
            /** Value */
            value: string;
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: number;
        };
        /** ComponentResult */
        ComponentResult: {
            /** Name */
            name: string;
            /** Applicable */
            applicable: boolean;
            /** Value */
            value: number | null;
            /** Weight */
            weight: number;
            /** Effective Weight */
            effective_weight: number;
            /** Contribution */
            contribution: number;
            /** Confidence */
            confidence: number | null;
            /** Reason */
            reason: string | null;
        };
        /** ConfidenceBands */
        ConfidenceBands: {
            /**
             * Accept
             * @default 0.8
             */
            accept: number;
            /**
             * Review
             * @default 0.6
             */
            review: number;
        };
        /** CreateJobOut */
        CreateJobOut: {
            job: components["schemas"]["JobOut"];
            /** Created */
            created: boolean;
        };
        /** EnqueuedOut */
        EnqueuedOut: {
            /**
             * Evaluation Id
             * Format: uuid
             */
            evaluation_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "succeeded" | "failed";
        };
        /** EnumOption */
        EnumOption: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** EvaluatePostingOut */
        EvaluatePostingOut: {
            job: components["schemas"]["JobOut"];
            /**
             * Evaluation Id
             * Format: uuid
             */
            evaluation_id: string;
            /** Created */
            created: boolean;
            /** Reused */
            reused: boolean;
        };
        /** EvaluationDetailOut */
        EvaluationDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Profile Version Id
             * Format: uuid
             */
            profile_version_id: string;
            /** Evaluator Version */
            evaluator_version: string | null;
            /** Catalog Hash */
            catalog_hash: string | null;
            /** Question Set Hash */
            question_set_hash: string | null;
            /** Model */
            model: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "succeeded" | "failed";
            /** Error */
            error: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Fit Results
             * @default []
             */
            fit_results: components["schemas"]["FitResultOut"][];
            signals?: components["schemas"]["SemanticSignals"] | null;
            /** Raw Typesafe Response */
            raw_typesafe_response?: components["schemas"]["RequestMeta"][] | null;
        };
        /** EvaluationIdsOut */
        EvaluationIdsOut: {
            /** Evaluation Ids */
            evaluation_ids: string[];
        };
        /** EvaluationOut */
        EvaluationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Profile Version Id
             * Format: uuid
             */
            profile_version_id: string;
            /** Evaluator Version */
            evaluator_version: string | null;
            /** Catalog Hash */
            catalog_hash: string | null;
            /** Question Set Hash */
            question_set_hash: string | null;
            /** Model */
            model: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "succeeded" | "failed";
            /** Error */
            error: string | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Fit Results
             * @default []
             */
            fit_results: components["schemas"]["FitResultOut"][];
        };
        /** Evidence */
        Evidence: {
            /** Line Id */
            line_id: string | null;
            /** Text */
            text: string | null;
            /** Probability */
            probability: number;
        };
        /** Explanation */
        Explanation: {
            /**
             * Section
             * @enum {string}
             */
            section: "strength" | "concern" | "uncertain" | "note";
            /** Text */
            text: string;
            /** Signal Ids */
            signal_ids: string[];
            /** Confidence */
            confidence: number | null;
            /** Evidence Line Id */
            evidence_line_id: string | null;
        };
        /** FitResultOut */
        FitResultOut: {
            /** Overall Score */
            overall_score: number;
            /** Base Score */
            base_score: number;
            /**
             * Status
             * @enum {string}
             */
            status: "STRONG_MATCH" | "GOOD_MATCH" | "REVIEW" | "LOW_MATCH" | "BLOCKED";
            /** Aggregate Confidence */
            aggregate_confidence: number;
            /** Needs Review */
            needs_review: boolean;
            /** Stale Semantics */
            stale_semantics: boolean;
            /** Components */
            components: components["schemas"]["ComponentResult"][];
            /** Penalties */
            penalties: components["schemas"]["Penalty"][];
            /** Hard Blockers */
            hard_blockers: components["schemas"]["HardBlocker"][];
            /** Possible Blockers */
            possible_blockers: components["schemas"]["HardBlocker"][];
            /** Skill Matches */
            skill_matches: components["schemas"]["SkillMatch"][];
            /** Missing Skills */
            missing_skills: components["schemas"]["MissingSkill"][];
            /** Explanations */
            explanations: components["schemas"]["Explanation"][];
            /** Uncertain Signals */
            uncertain_signals: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Evaluation Id
             * Format: uuid
             */
            evaluation_id: string;
            /**
             * Profile Version Id
             * Format: uuid
             */
            profile_version_id: string;
            /**
             * Scoring Config Id
             * Format: uuid
             */
            scoring_config_id: string;
            /** Scoring Config Version */
            scoring_config_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardBlocker */
        HardBlocker: {
            /** Type */
            type: string;
            /** Reason */
            reason: string;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: string | null;
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Evaluator
             * @enum {string}
             */
            evaluator: "typesafe" | "fake";
            /** Model */
            model: string;
            /** Api Key Configured */
            api_key_configured: boolean;
            /** Queue Depth */
            queue_depth: number;
        };
        /** JobDetailOut */
        JobDetailOut: {
            job: components["schemas"]["JobOut"];
            fit_result: components["schemas"]["FitResultOut"] | null;
            evaluation: components["schemas"]["EvaluationDetailOut"] | null;
            latest_evaluation: components["schemas"]["EvaluationOut"] | null;
        };
        /** JobListOut */
        JobListOut: {
            /** Rows */
            rows: components["schemas"]["JobRowOut"][];
            /** Total Filtered */
            total_filtered: number;
            stats: components["schemas"]["JobStatsOut"];
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Location */
            location: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "linkedin" | "indeed" | "company_site" | "recruiter_email" | "manual" | "other";
            /** Source Url */
            source_url: string | null;
            /** External Id */
            external_id: string | null;
            /** Salary Text */
            salary_text: string | null;
            /** Description */
            description: string;
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
        };
        /** JobPostingIn */
        JobPostingIn: {
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Location */
            location?: string | null;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "linkedin" | "indeed" | "company_site" | "recruiter_email" | "manual" | "other";
            /** Source Url */
            source_url?: string | null;
            /** Salary Text */
            salary_text?: string | null;
            /** External Id */
            external_id?: string | null;
        };
        /** JobRowOut */
        JobRowOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Location */
            location: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "linkedin" | "indeed" | "company_site" | "recruiter_email" | "manual" | "other";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Overall Score */
            overall_score: number | null;
            /** Status */
            status: ("STRONG_MATCH" | "GOOD_MATCH" | "REVIEW" | "LOW_MATCH" | "BLOCKED") | null;
            /** Aggregate Confidence */
            aggregate_confidence: number | null;
            /** Needs Review */
            needs_review: boolean | null;
            /** Role Family */
            role_family: string | null;
            /** Seniority */
            seniority: string | null;
            /** Domain */
            domain: string | null;
            /** Work Arrangement */
            work_arrangement: string | null;
            /** Kmp Requirement */
            kmp_requirement: string | null;
            /** Work Authorization Signal */
            work_authorization_signal: string | null;
            /** Android Relevance */
            android_relevance: number | null;
            /** Security Clearance Required */
            security_clearance_required: number | null;
            /** Evaluation Status */
            evaluation_status: ("pending" | "running" | "succeeded" | "failed") | null;
            /** Evaluation Error */
            evaluation_error: string | null;
            /** Latest Evaluation Id */
            latest_evaluation_id: string | null;
        };
        /** JobStatsOut */
        JobStatsOut: {
            /** Total */
            total: number;
            /** Evaluated */
            evaluated: number;
            /** Strong */
            strong: number;
            /** Good */
            good: number;
            /** Review */
            review: number;
            /** Low */
            low: number;
            /** Blocked */
            blocked: number;
            /** Pending */
            pending: number;
            /** Failed */
            failed: number;
        };
        /** ManagementHeavyForIc */
        ManagementHeavyForIc: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Points
             * @default 15
             */
            points: number;
            /**
             * Min Intensity
             * @default 2.5
             */
            min_intensity: number;
        };
        /** MetaOut */
        MetaOut: {
            /** Enums */
            enums: {
                [key: string]: components["schemas"]["EnumOption"][];
            };
            /** Default Tracked Skills */
            default_tracked_skills: components["schemas"]["TrackedSkill"][];
            /** Evaluator Version */
            evaluator_version: string;
            /** Model */
            model: string;
        };
        /** MissingRequiredSkill */
        MissingRequiredSkill: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Points None
             * @default 10
             */
            points_none: number;
            /**
             * Points Weak
             * @default 5
             */
            points_weak: number;
            /**
             * Cap
             * @default 20
             */
            cap: number;
        };
        /** MissingSkill */
        MissingSkill: {
            /** Skill */
            skill: string;
            /**
             * Source
             * @enum {string}
             */
            source: "tracked_skill" | "requirement_line";
            /**
             * Importance
             * @enum {string}
             */
            importance: "critical" | "important" | "nice_to_have";
            /**
             * Candidate Evidence
             * @enum {string}
             */
            candidate_evidence: "none" | "weak" | "partial";
            /**
             * Impact
             * @enum {string}
             */
            impact: "blocker" | "significant" | "minor";
            /** Line Ids */
            line_ids: string[];
        };
        /** MissingSkillsConfig */
        MissingSkillsConfig: {
            /**
             * Min Line Kind Probability
             * @default 0.6
             */
            min_line_kind_probability: number;
            /**
             * Min Line Skill None Probability
             * @default 0.5
             */
            min_line_skill_none_probability: number;
        };
        /** NoulSignal */
        NoulSignal: {
            /** Probability */
            probability: number;
            /** Derived Confidence */
            derived_confidence: number;
        };
        /** Penalties */
        Penalties: {
            /**
             * @default {
             *       "enabled": true,
             *       "points": 10,
             *       "min_cross_platform_intensity": 2.5,
             *       "cross_platform_families": [
             *         "flutter",
             *         "react_native"
             *       ],
             *       "min_tech_centrality": 2
             *     }
             */
            avoided_tech_heavy: components["schemas"]["AvoidedTechHeavy"];
            /**
             * @default {
             *       "enabled": true,
             *       "points": 15,
             *       "min_intensity": 2.5
             *     }
             */
            management_heavy_for_ic: components["schemas"]["ManagementHeavyForIc"];
            /**
             * @default {
             *       "enabled": true,
             *       "points": 10,
             *       "max_preferred_probability": 0.4,
             *       "max_unclear_probability": 0.5
             *     }
             */
            seniority_mismatch: components["schemas"]["SeniorityMismatch"];
            /**
             * @default {
             *       "enabled": true,
             *       "points": 10,
             *       "max_centrality": 1
             *     }
             */
            required_tech_weak: components["schemas"]["RequiredTechWeak"];
            /**
             * @default {
             *       "enabled": true,
             *       "points_none": 10,
             *       "points_weak": 5,
             *       "cap": 20
             *     }
             */
            missing_required_skill: components["schemas"]["MissingRequiredSkill"];
        };
        /** Penalty */
        Penalty: {
            /** Type */
            type: string;
            /** Points */
            points: number;
            /** Reason */
            reason: string;
            /** Signal Ids */
            signal_ids: string[];
        };
        /** ProfileSaveOut */
        ProfileSaveOut: {
            profile: components["schemas"]["CandidateProfile"];
            /**
             * Change Kind
             * @enum {string}
             */
            change_kind: "none" | "scoring_only" | "semantic";
            /** Affected Jobs */
            affected_jobs: number;
            /** Rescored */
            rescored: number;
        };
        /** ReevaluateIn */
        ReevaluateIn: {
            /** Job Ids */
            job_ids?: string[] | null;
        };
        /** RequestMeta */
        RequestMeta: {
            /** Request Id */
            request_id: string | null;
            /**
             * State Kind
             * @enum {string}
             */
            state_kind: "job" | "fit";
            /** Question Count */
            question_count: number;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Latency Ms */
            latency_ms: number;
            /** Raw Response */
            raw_response: {
                [key: string]: unknown;
            };
        };
        /** RequestQuestionOut */
        RequestQuestionOut: {
            /** Id */
            id: string;
            /**
             * State
             * @enum {string}
             */
            state: "job" | "fit";
            /** Body */
            body: {
                [key: string]: unknown;
            };
        };
        /** RequestRebuildOut */
        RequestRebuildOut: {
            /** States */
            states: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Questions */
            questions: components["schemas"]["RequestQuestionOut"][];
            /** Question Set Hash */
            question_set_hash: string;
            /** Hash Matches */
            hash_matches: boolean;
        };
        /** RequiredTechWeak */
        RequiredTechWeak: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Points
             * @default 10
             */
            points: number;
            /**
             * Max Centrality
             * @default 1
             */
            max_centrality: number;
        };
        /** RequirementLine */
        RequirementLine: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            kind: components["schemas"]["ChoiceSignal"];
            skill: components["schemas"]["ChoiceSignal"];
            evidence: components["schemas"]["ScoreSignal"];
        };
        /** RescoreOut */
        RescoreOut: {
            /** Version */
            version: number;
            /** Rescored */
            rescored: number;
        };
        /** ResumeTextOut */
        ResumeTextOut: {
            /** Text */
            text: string;
        };
        /** ScoreSignal */
        ScoreSignal: {
            /** Score */
            score: number;
            /** Levels */
            levels: number;
            /** Normalized */
            normalized: number;
            /** Probabilities */
            probabilities: {
                [key: string]: number;
            };
            /** Confidence */
            confidence: number;
        };
        /** ScoringConfig */
        ScoringConfig: {
            /**
             * @default {
             *       "technical": 30,
             *       "android": 20,
             *       "seniority": 15,
             *       "role_preference": 10,
             *       "platform": 10,
             *       "domain": 5,
             *       "work_arrangement": 5,
             *       "management": 5
             *     }
             */
            weights: components["schemas"]["Weights"];
            /**
             * Neutral Platform Preference
             * @default 0.5
             */
            neutral_platform_preference: number;
            /**
             * Domain Preference Blend
             * @default 0.5
             */
            domain_preference_blend: number;
            /**
             * Relocation Location Factor
             * @default 0.5
             */
            relocation_location_factor: number;
            /** Arrangement Matrix */
            arrangement_matrix?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /**
             * @default {
             *       "avoided_tech_heavy": {
             *         "cross_platform_families": [
             *           "flutter",
             *           "react_native"
             *         ],
             *         "enabled": true,
             *         "min_cross_platform_intensity": 2.5,
             *         "min_tech_centrality": 2,
             *         "points": 10
             *       },
             *       "management_heavy_for_ic": {
             *         "enabled": true,
             *         "min_intensity": 2.5,
             *         "points": 15
             *       },
             *       "seniority_mismatch": {
             *         "enabled": true,
             *         "max_preferred_probability": 0.4,
             *         "max_unclear_probability": 0.5,
             *         "points": 10
             *       },
             *       "required_tech_weak": {
             *         "enabled": true,
             *         "max_centrality": 1,
             *         "points": 10
             *       },
             *       "missing_required_skill": {
             *         "cap": 20,
             *         "enabled": true,
             *         "points_none": 10,
             *         "points_weak": 5
             *       }
             *     }
             */
            penalties: components["schemas"]["Penalties"];
            /**
             * @default {
             *       "threshold": 0.8,
             *       "possible_threshold": 0.5,
             *       "security_clearance": {
             *         "enabled": true
             *       },
             *       "us_citizenship": {
             *         "enabled": true
             *       },
             *       "no_sponsorship": {
             *         "enabled": true
             *       },
             *       "relocation": {
             *         "enabled": true
             *       },
             *       "onsite_location": {
             *         "enabled": true
             *       },
             *       "technology_mismatch": {
             *         "avoid_core_probability": 0.8,
             *         "enabled": true,
             *         "required_absent_probability": 0.9
             *       },
             *       "seniority_far_below": {
             *         "enabled": true,
             *         "min_steps_below": 2
             *       }
             *     }
             */
            blockers: components["schemas"]["Blockers"];
            /**
             * @default {
             *       "strong_match": 85,
             *       "good_match": 70,
             *       "review": 55
             *     }
             */
            status_thresholds: components["schemas"]["StatusThresholds"];
            /**
             * @default {
             *       "accept": 0.8,
             *       "review": 0.6
             *     }
             */
            confidence_bands: components["schemas"]["ConfidenceBands"];
            /**
             * @default {
             *       "min_line_kind_probability": 0.6,
             *       "min_line_skill_none_probability": 0.5
             *     }
             */
            missing_skills: components["schemas"]["MissingSkillsConfig"];
            /**
             * Evidence Min Probability
             * @default 0.5
             */
            evidence_min_probability: number;
        };
        /** ScoringSettingsOut */
        ScoringSettingsOut: {
            /** Version */
            version: number;
            config: components["schemas"]["ScoringConfig"];
            defaults: components["schemas"]["ScoringConfig"];
        };
        /**
         * SemanticSignals
         * @description All semantic signals and metadata except raw request data (what evaluations store in `signals`).
         */
        SemanticSignals: {
            role_family: components["schemas"]["ChoiceSignal"];
            android_relevance: components["schemas"]["ScoreSignal"];
            seniority: components["schemas"]["ChoiceSignal"];
            title_level: components["schemas"]["ChoiceSignal"];
            staff_ic_signal: components["schemas"]["NoulSignal"];
            management_intensity: components["schemas"]["ScoreSignal"];
            kmp_requirement: components["schemas"]["ChoiceSignal"];
            cross_platform_intensity: components["schemas"]["ScoreSignal"];
            domain: components["schemas"]["ChoiceSignal"];
            work_arrangement: components["schemas"]["ChoiceSignal"];
            requires_relocation: components["schemas"]["NoulSignal"];
            security_clearance_required: components["schemas"]["NoulSignal"];
            us_citizenship_required: components["schemas"]["NoulSignal"];
            work_authorization_signal: components["schemas"]["ChoiceSignal"];
            min_years_required: components["schemas"]["ChoiceSignal"];
            technical_fit: components["schemas"]["ScoreSignal"];
            seniority_fit: components["schemas"]["ScoreSignal"];
            domain_fit: components["schemas"]["ScoreSignal"];
            role_preference_fit: components["schemas"]["ScoreSignal"] | null;
            location_match: components["schemas"]["ChoiceSignal"] | null;
            /** Skills */
            skills: {
                [key: string]: components["schemas"]["SkillSignal"];
            };
            /** Technologies */
            technologies: {
                [key: string]: components["schemas"]["ScoreSignal"];
            };
            /** Lines */
            lines: components["schemas"]["RequirementLine"][];
            /** All Lines */
            all_lines: {
                [key: string]: string;
            };
            /** Evidence */
            evidence: {
                [key: string]: components["schemas"]["Evidence"];
            };
            /** Model */
            model: string;
            /** Evaluator Version */
            evaluator_version: string;
            /** Catalog Hash */
            catalog_hash: string;
            /** Question Set Hash */
            question_set_hash: string;
        };
        /** SeniorityFarBelow */
        SeniorityFarBelow: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Min Steps Below
             * @default 2
             */
            min_steps_below: number;
        };
        /** SeniorityMismatch */
        SeniorityMismatch: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Points
             * @default 10
             */
            points: number;
            /**
             * Max Preferred Probability
             * @default 0.4
             */
            max_preferred_probability: number;
            /**
             * Max Unclear Probability
             * @default 0.5
             */
            max_unclear_probability: number;
        };
        /** SkillMatch */
        SkillMatch: {
            /** Skill */
            skill: string;
            /**
             * Requirement Level
             * @enum {string}
             */
            requirement_level: "required" | "preferred" | "mentioned";
            /** Candidate Match */
            candidate_match: number;
            /** Confidence */
            confidence: number;
            /** Evidence Line Ids */
            evidence_line_ids: string[];
        };
        /** SkillSignal */
        SkillSignal: {
            requirement: components["schemas"]["ChoiceSignal"];
            evidence: components["schemas"]["ScoreSignal"];
        };
        /** StatusThresholds */
        StatusThresholds: {
            /**
             * Strong Match
             * @default 85
             */
            strong_match: number;
            /**
             * Good Match
             * @default 70
             */
            good_match: number;
            /**
             * Review
             * @default 55
             */
            review: number;
        };
        /** TechnologyMismatch */
        TechnologyMismatch: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Avoid Core Probability
             * @default 0.8
             */
            avoid_core_probability: number;
            /**
             * Required Absent Probability
             * @default 0.9
             */
            required_absent_probability: number;
        };
        /** Toggle */
        Toggle: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** TrackedSkill */
        TrackedSkill: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Weights */
        Weights: {
            /**
             * Technical
             * @default 30
             */
            technical: number;
            /**
             * Android
             * @default 20
             */
            android: number;
            /**
             * Seniority
             * @default 15
             */
            seniority: number;
            /**
             * Role Preference
             * @default 10
             */
            role_preference: number;
            /**
             * Platform
             * @default 10
             */
            platform: number;
            /**
             * Domain
             * @default 5
             */
            domain: number;
            /**
             * Work Arrangement
             * @default 5
             */
            work_arrangement: number;
            /**
             * Management
             * @default 5
             */
            management: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfile"];
                };
            };
        };
    };
    put_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileSaveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_resume_api_profile_resume_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_resume_api_profile_resume_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeTextOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                q?: string | null;
                min_score?: number | null;
                status?: string[] | null;
                company?: string | null;
                role_family?: string[] | null;
                seniority?: string[] | null;
                domain?: string[] | null;
                work_arrangement?: string[] | null;
                kmp_requirement?: string[] | null;
                min_android_relevance?: number | null;
                clearance?: ("required" | "possible" | "not_required") | null;
                work_authorization_signal?: string[] | null;
                source?: string[] | null;
                evaluation_status?: string[] | null;
                needs_review?: boolean | null;
                sort?: "score" | "confidence" | "company" | "created_at" | "android_relevance";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPostingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_create_api_jobs_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_job_api_jobs__job_id__evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueuedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reevaluate_api_jobs_reevaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReevaluateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationIdsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_posting_api_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobPostingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluatePostingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluations_api_evaluations_get: {
        parameters: {
            query: {
                job_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_api_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_request_api_evaluations__evaluation_id__request_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRebuildOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoring_api_settings_scoring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringSettingsOut"];
                };
            };
        };
    };
    put_scoring_api_settings_scoring_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoringConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
