"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-17 01:09:56.522961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('salary_text', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('current_fit_result_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_content_hash'), ['content_hash'], unique=False)

    op.create_table('profile_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('blocker_facts', sa.JSON(), nullable=False),
    sa.Column('tracked_skills', sa.JSON(), nullable=False),
    sa.Column('semantic_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('job_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('profile_version_id', sa.Uuid(), nullable=False),
    sa.Column('evaluator_version', sa.String(length=32), nullable=True),
    sa.Column('catalog_hash', sa.String(length=64), nullable=True),
    sa.Column('question_set_hash', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('raw_typesafe_response', sa.JSON(), nullable=True),
    sa.Column('role_family', sa.String(length=32), nullable=True),
    sa.Column('seniority', sa.String(length=32), nullable=True),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.Column('work_arrangement', sa.String(length=32), nullable=True),
    sa.Column('kmp_requirement', sa.String(length=32), nullable=True),
    sa.Column('work_authorization_signal', sa.String(length=64), nullable=True),
    sa.Column('android_relevance', sa.Float(), nullable=True),
    sa.Column('technical_fit', sa.Float(), nullable=True),
    sa.Column('seniority_fit', sa.Float(), nullable=True),
    sa.Column('domain_fit', sa.Float(), nullable=True),
    sa.Column('management_intensity', sa.Float(), nullable=True),
    sa.Column('cross_platform_intensity', sa.Float(), nullable=True),
    sa.Column('staff_ic_signal', sa.Float(), nullable=True),
    sa.Column('requires_relocation', sa.Float(), nullable=True),
    sa.Column('security_clearance_required', sa.Float(), nullable=True),
    sa.Column('us_citizenship_required', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_version_id'], ['profile_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_evaluations_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_evaluations_status'), ['status'], unique=False)

    op.create_table('fit_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('profile_version_id', sa.Uuid(), nullable=False),
    sa.Column('scoring_config_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('aggregate_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('stale_semantics', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['job_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_version_id'], ['profile_versions.id'], ),
    sa.ForeignKeyConstraint(['scoring_config_id'], ['scoring_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fit_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fit_results_evaluation_id'), ['evaluation_id'], unique=False)

    # Circular reference: added after fit_results exists (keeps the migration PostgreSQL-safe).
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_job_current_fit_result', 'fit_results', ['current_fit_result_id'], ['id'],
                                    ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_current_fit_result', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fit_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fit_results_evaluation_id'))

    op.drop_table('fit_results')
    with op.batch_alter_table('job_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_evaluations_status'))
        batch_op.drop_index(batch_op.f('ix_job_evaluations_job_id'))

    op.drop_table('job_evaluations')
    op.drop_table('scoring_configs')
    op.drop_table('profile_versions')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_content_hash'))

    op.drop_table('job_postings')
    # ### end Alembic commands ###
