"""import

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-17 14:41:50.274384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), server_default='ready', nullable=False))
        batch_op.add_column(sa.Column('import_source', sa.String(length=16), server_default='paste', nullable=False))
        batch_op.create_index(batch_op.f('ix_job_postings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_status'))
        batch_op.drop_column('import_source')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
